name: ytcm
description: YTC Messenger client
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0
  http: ^1.2.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  path: ^1.9.0
  intl: ^0.19.0
  provider: ^6.1.2
  emoji_picker_flutter: ^2.2.0
  flutter_local_notifications: ^17.2.4
  workmanager: ^0.9.0
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1
  file_picker: ^8.0.7
  mime: ^2.0.0
  open_filex: ^4.5.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/icon/app_icon.png
  linux: true
  windows: false
  web:
    generate: false

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png
    - SVGs/regular/

  fonts:
    - family: Geist
      fonts:
        - asset: fonts/Geist[wght].ttf
        - asset: fonts/Geist-Italic[wght].ttf
          style: italic
